# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 607)
        MainWindow.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_show = QtWidgets.QLabel(self.centralwidget)
        self.Image_show.setGeometry(QtCore.QRect(0, 50, 640, 511))
        self.Image_show.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Image_show.setText("")
        self.Image_show.setObjectName("Image_show")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 450, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.btn_close_detection = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close_detection.setEnabled(False)
        self.btn_close_detection.setGeometry(QtCore.QRect(650, 500, 121, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.btn_close_detection.setFont(font)
        self.btn_close_detection.setObjectName("btn_close_detection")
        self.btn_open_detection = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_detection.setGeometry(QtCore.QRect(790, 500, 121, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.btn_open_detection.setFont(font)
        self.btn_open_detection.setObjectName("btn_open_detection")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(650, 360, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_speed = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_speed.setGeometry(QtCore.QRect(850, 360, 61, 31))
        self.lineEdit_speed.setStyleSheet("  QLineEdit {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.lineEdit_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 66, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_speed_100 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_speed_100.setGeometry(QtCore.QRect(780, 360, 61, 30))
        self.btn_speed_100.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_speed_100.setObjectName("btn_speed_100")
        self.label_j2 = QtWidgets.QLabel(self.centralwidget)
        self.label_j2.setGeometry(QtCore.QRect(850, 160, 61, 31))
        self.label_j2.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j2.setObjectName("label_j2")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(840, 16, 71, 30))
        self.btn_zero.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_zero.setObjectName("btn_zero")
        self.btn_step_10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_10.setGeometry(QtCore.QRect(783, 311, 28, 30))
        self.btn_step_10.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_10.setObjectName("btn_step_10")
        self.btn_enable_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enable_off.setGeometry(QtCore.QRect(850, 66, 61, 30))
        self.btn_enable_off.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 15px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}")
        self.btn_enable_off.setObjectName("btn_enable_off")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_j1 = QtWidgets.QLabel(self.centralwidget)
        self.label_j1.setGeometry(QtCore.QRect(850, 110, 61, 31))
        self.label_j1.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j1.setObjectName("label_j1")
        self.btn_j4_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j4_subtract.setGeometry(QtCore.QRect(780, 260, 61, 30))
        self.btn_j4_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j4_subtract.setObjectName("btn_j4_subtract")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 410, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(660, 16, 71, 30))
        self.btn_start.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_start.setObjectName("btn_start")
        self.btn_speed_30 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_speed_30.setGeometry(QtCore.QRect(710, 360, 61, 30))
        self.btn_speed_30.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_speed_30.setObjectName("btn_speed_30")
        self.btn_reduce = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reduce.setGeometry(QtCore.QRect(750, 16, 71, 30))
        self.btn_reduce.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_reduce.setObjectName("btn_reduce")
        self.label_j3 = QtWidgets.QLabel(self.centralwidget)
        self.label_j3.setGeometry(QtCore.QRect(850, 210, 61, 31))
        self.label_j3.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j3.setObjectName("label_j3")
        self.label_j4 = QtWidgets.QLabel(self.centralwidget)
        self.label_j4.setGeometry(QtCore.QRect(850, 260, 61, 31))
        self.label_j4.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j4.setObjectName("label_j4")
        self.btn_j2_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j2_add.setGeometry(QtCore.QRect(710, 160, 61, 30))
        self.btn_j2_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j2_add.setObjectName("btn_j2_add")
        self.btn_clip_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clip_open.setGeometry(QtCore.QRect(710, 410, 61, 30))
        self.btn_clip_open.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_clip_open.setObjectName("btn_clip_open")
        self.btn_step_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_1.setGeometry(QtCore.QRect(711, 311, 28, 30))
        self.btn_step_1.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_1.setIconSize(QtCore.QSize(16, 16))
        self.btn_step_1.setObjectName("btn_step_1")
        self.btn_step_15 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_15.setGeometry(QtCore.QRect(819, 311, 28, 30))
        self.btn_step_15.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_15.setObjectName("btn_step_15")
        self.btn_j3_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j3_add.setGeometry(QtCore.QRect(710, 210, 61, 30))
        self.btn_j3_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j3_add.setObjectName("btn_j3_add")
        self.lineEdit_step = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_step.setGeometry(QtCore.QRect(850, 310, 61, 31))
        self.lineEdit_step.setStyleSheet("  QLineEdit {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.lineEdit_step.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.btn_j1_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j1_subtract.setGeometry(QtCore.QRect(780, 110, 61, 30))
        self.btn_j1_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j1_subtract.setObjectName("btn_j1_subtract")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(650, 210, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btn_clip_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clip_close.setGeometry(QtCore.QRect(850, 410, 61, 30))
        self.btn_clip_close.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_clip_close.setObjectName("btn_clip_close")
        self.btn_j2_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j2_subtract.setGeometry(QtCore.QRect(780, 160, 61, 30))
        self.btn_j2_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j2_subtract.setObjectName("btn_j2_subtract")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(650, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.btn_enable_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enable_on.setGeometry(QtCore.QRect(710, 66, 61, 30))
        self.btn_enable_on.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 15px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}")
        self.btn_enable_on.setObjectName("btn_enable_on")
        self.btn_step_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_5.setGeometry(QtCore.QRect(747, 311, 28, 30))
        self.btn_step_5.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_5.setObjectName("btn_step_5")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(650, 310, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(650, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.btn_j3_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j3_subtract.setGeometry(QtCore.QRect(780, 210, 61, 30))
        self.btn_j3_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j3_subtract.setObjectName("btn_j3_subtract")
        self.btn_j1_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j1_add.setGeometry(QtCore.QRect(710, 110, 61, 30))
        self.btn_j1_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j1_add.setObjectName("btn_j1_add")
        self.btn_j4_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j4_add.setGeometry(QtCore.QRect(710, 260, 61, 30))
        self.btn_j4_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j4_add.setObjectName("btn_j4_add")
        self.cbx_Ispick = QtWidgets.QCheckBox(self.centralwidget)
        self.cbx_Ispick.setGeometry(QtCore.QRect(641, 460, 79, 19))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.cbx_Ispick.setFont(font)
        self.cbx_Ispick.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbx_Ispick.setAutoFillBackground(False)
        self.cbx_Ispick.setCheckable(True)
        self.cbx_Ispick.setChecked(False)
        self.cbx_Ispick.setObjectName("cbx_Ispick")
        self.cbx_Ispick_color = QtWidgets.QCheckBox(self.centralwidget)
        self.cbx_Ispick_color.setGeometry(QtCore.QRect(740, 460, 79, 19))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.cbx_Ispick_color.setFont(font)
        self.cbx_Ispick_color.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbx_Ispick_color.setAutoFillBackground(False)
        self.cbx_Ispick_color.setCheckable(True)
        self.cbx_Ispick_color.setChecked(False)
        self.cbx_Ispick_color.setObjectName("cbx_Ispick_color")
        self.cbx_Ispick_shape = QtWidgets.QCheckBox(self.centralwidget)
        self.cbx_Ispick_shape.setGeometry(QtCore.QRect(830, 460, 79, 19))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.cbx_Ispick_shape.setFont(font)
        self.cbx_Ispick_shape.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbx_Ispick_shape.setAutoFillBackground(False)
        self.cbx_Ispick_shape.setCheckable(True)
        self.cbx_Ispick_shape.setChecked(False)
        self.cbx_Ispick_shape.setObjectName("cbx_Ispick_shape")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于视觉与语音的机械臂物体分类"))
        self.label_2.setText(_translate("MainWindow", "基于视觉与语音的机械臂物体分类"))
        self.btn_close_detection.setText(_translate("MainWindow", "关闭检测"))
        self.btn_open_detection.setText(_translate("MainWindow", "开启检测"))
        self.label_12.setText(_translate("MainWindow", "速 度："))
        self.lineEdit_speed.setText(_translate("MainWindow", "100"))
        self.label_6.setText(_translate("MainWindow", "使 能："))
        self.btn_speed_100.setText(_translate("MainWindow", "100"))
        self.label_j2.setText(_translate("MainWindow", "0"))
        self.btn_zero.setText(_translate("MainWindow", "归位"))
        self.btn_step_10.setText(_translate("MainWindow", "10"))
        self.btn_enable_off.setText(_translate("MainWindow", "OFF"))
        self.label_4.setText(_translate("MainWindow", "关节4："))
        self.label_j1.setText(_translate("MainWindow", "0"))
        self.btn_j4_subtract.setText(_translate("MainWindow", "J4-"))
        self.label_5.setText(_translate("MainWindow", "夹 爪："))
        self.btn_start.setText(_translate("MainWindow", "启动"))
        self.btn_speed_30.setText(_translate("MainWindow", "30"))
        self.btn_reduce.setText(_translate("MainWindow", "复位"))
        self.label_j3.setText(_translate("MainWindow", "0"))
        self.label_j4.setText(_translate("MainWindow", "0"))
        self.btn_j2_add.setText(_translate("MainWindow", "J2+"))
        self.btn_clip_open.setText(_translate("MainWindow", "开"))
        self.btn_step_1.setText(_translate("MainWindow", "1"))
        self.btn_step_15.setText(_translate("MainWindow", "15"))
        self.btn_j3_add.setText(_translate("MainWindow", "J3+"))
        self.lineEdit_step.setText(_translate("MainWindow", "5"))
        self.btn_j1_subtract.setText(_translate("MainWindow", "J1-"))
        self.label_10.setText(_translate("MainWindow", "关节3："))
        self.btn_clip_close.setText(_translate("MainWindow", "关"))
        self.btn_j2_subtract.setText(_translate("MainWindow", "J2-"))
        self.label_11.setText(_translate("MainWindow", "关节1："))
        self.btn_enable_on.setText(_translate("MainWindow", "ON"))
        self.btn_step_5.setText(_translate("MainWindow", "5"))
        self.label_13.setText(_translate("MainWindow", "步 长："))
        self.label_14.setText(_translate("MainWindow", "关节2："))
        self.btn_j3_subtract.setText(_translate("MainWindow", "J3-"))
        self.btn_j1_add.setText(_translate("MainWindow", "J1+"))
        self.btn_j4_add.setText(_translate("MainWindow", "J4+"))
        self.cbx_Ispick.setText(_translate("MainWindow", " 抓 取："))
        self.cbx_Ispick_color.setText(_translate("MainWindow", " 颜 色："))
        self.cbx_Ispick_shape.setText(_translate("MainWindow", " 形 状："))
