# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 570)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 58, 811, 421))
        self.tableView.setStyleSheet("")
        self.tableView.setObjectName("tableView")
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(214, 491, 44, 30))
        self.btn_del.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 10px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_del.setObjectName("btn_del")
        self.btn_move_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_move_up.setGeometry(QtCore.QRect(14, 491, 44, 30))
        self.btn_move_up.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 10px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_move_up.setObjectName("btn_move_up")
        self.btn_move_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_move_down.setGeometry(QtCore.QRect(64, 491, 44, 30))
        self.btn_move_down.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 10px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_move_down.setObjectName("btn_move_down")
        self.btn_stick = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stick.setGeometry(QtCore.QRect(164, 491, 44, 30))
        self.btn_stick.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 10px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_stick.setObjectName("btn_stick")
        self.btn_copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy.setGeometry(QtCore.QRect(114, 491, 44, 30))
        self.btn_copy.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 10px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_copy.setObjectName("btn_copy")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(264, 491, 86, 30))
        self.btn_clear.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 10px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_save_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_file.setGeometry(QtCore.QRect(70, 21, 44, 30))
        self.btn_save_file.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_save_file.setObjectName("btn_save_file")
        self.btn_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_file.setGeometry(QtCore.QRect(11, 21, 44, 30))
        self.btn_open_file.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_open_file.setObjectName("btn_open_file")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(830, 164, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(830, 214, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(830, 264, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(830, 314, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(830, 464, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_j1_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j1_add.setGeometry(QtCore.QRect(890, 164, 61, 30))
        self.btn_j1_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j1_add.setObjectName("btn_j1_add")
        self.btn_j1_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j1_subtract.setGeometry(QtCore.QRect(960, 164, 61, 30))
        self.btn_j1_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j1_subtract.setObjectName("btn_j1_subtract")
        self.label_j1 = QtWidgets.QLabel(self.centralwidget)
        self.label_j1.setGeometry(QtCore.QRect(1030, 164, 61, 31))
        self.label_j1.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j1.setObjectName("label_j1")
        self.btn_j2_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j2_add.setGeometry(QtCore.QRect(890, 214, 61, 30))
        self.btn_j2_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j2_add.setObjectName("btn_j2_add")
        self.btn_j2_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j2_subtract.setGeometry(QtCore.QRect(960, 214, 61, 30))
        self.btn_j2_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j2_subtract.setObjectName("btn_j2_subtract")
        self.label_j2 = QtWidgets.QLabel(self.centralwidget)
        self.label_j2.setGeometry(QtCore.QRect(1030, 214, 61, 31))
        self.label_j2.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j2.setObjectName("label_j2")
        self.btn_j3_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j3_add.setGeometry(QtCore.QRect(890, 264, 61, 30))
        self.btn_j3_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j3_add.setObjectName("btn_j3_add")
        self.label_j3 = QtWidgets.QLabel(self.centralwidget)
        self.label_j3.setGeometry(QtCore.QRect(1030, 264, 61, 31))
        self.label_j3.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j3.setObjectName("label_j3")
        self.btn_j3_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j3_subtract.setGeometry(QtCore.QRect(960, 264, 61, 30))
        self.btn_j3_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j3_subtract.setObjectName("btn_j3_subtract")
        self.btn_j4_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j4_add.setGeometry(QtCore.QRect(890, 314, 61, 30))
        self.btn_j4_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j4_add.setObjectName("btn_j4_add")
        self.label_j4 = QtWidgets.QLabel(self.centralwidget)
        self.label_j4.setGeometry(QtCore.QRect(1030, 314, 61, 31))
        self.label_j4.setStyleSheet("QLabel {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.label_j4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j4.setObjectName("label_j4")
        self.btn_j4_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_j4_subtract.setGeometry(QtCore.QRect(960, 314, 61, 30))
        self.btn_j4_subtract.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_j4_subtract.setObjectName("btn_j4_subtract")
        self.btn_clip_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clip_open.setGeometry(QtCore.QRect(890, 464, 61, 30))
        self.btn_clip_open.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_clip_open.setObjectName("btn_clip_open")
        self.btn_clip_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clip_close.setGeometry(QtCore.QRect(1030, 464, 61, 30))
        self.btn_clip_close.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_clip_close.setObjectName("btn_clip_close")
        self.btn_reduce = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reduce.setGeometry(QtCore.QRect(930, 20, 71, 30))
        self.btn_reduce.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_reduce.setObjectName("btn_reduce")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(1020, 20, 71, 30))
        self.btn_zero.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_zero.setObjectName("btn_zero")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(840, 20, 71, 30))
        self.btn_start.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_start.setObjectName("btn_start")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(830, 364, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btn_step_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_1.setGeometry(QtCore.QRect(891, 365, 28, 30))
        self.btn_step_1.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_1.setIconSize(QtCore.QSize(16, 16))
        self.btn_step_1.setObjectName("btn_step_1")
        self.btn_step_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_5.setGeometry(QtCore.QRect(927, 365, 28, 30))
        self.btn_step_5.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_5.setObjectName("btn_step_5")
        self.btn_step_10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_10.setGeometry(QtCore.QRect(963, 365, 28, 30))
        self.btn_step_10.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_10.setObjectName("btn_step_10")
        self.btn_step_15 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step_15.setGeometry(QtCore.QRect(999, 365, 28, 30))
        self.btn_step_15.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step_15.setObjectName("btn_step_15")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(830, 414, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.btn_speed_30 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_speed_30.setGeometry(QtCore.QRect(890, 414, 61, 30))
        self.btn_speed_30.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_speed_30.setObjectName("btn_speed_30")
        self.btn_speed_100 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_speed_100.setGeometry(QtCore.QRect(960, 414, 61, 30))
        self.btn_speed_100.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_speed_100.setObjectName("btn_speed_100")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(830, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_speed = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_speed.setGeometry(QtCore.QRect(1030, 414, 61, 31))
        self.lineEdit_speed.setStyleSheet("  QLineEdit {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.lineEdit_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.lineEdit_step = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_step.setGeometry(QtCore.QRect(1030, 364, 61, 31))
        self.lineEdit_step.setStyleSheet("  QLineEdit {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.lineEdit_step.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(526, 21, 44, 30))
        self.btn_run.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_run.setObjectName("btn_run")
        self.lineEdit_recur = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_recur.setGeometry(QtCore.QRect(459, 21, 61, 30))
        self.lineEdit_recur.setStyleSheet("  QLineEdit {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.lineEdit_recur.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_recur.setObjectName("lineEdit_recur")
        self.btn_step = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step.setGeometry(QtCore.QRect(626, 21, 44, 30))
        self.btn_step.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_step.setObjectName("btn_step")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(676, 21, 44, 30))
        self.btn_add.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_add.setObjectName("btn_add")
        self.btn_renew = QtWidgets.QPushButton(self.centralwidget)
        self.btn_renew.setGeometry(QtCore.QRect(776, 21, 44, 30))
        self.btn_renew.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_renew.setObjectName("btn_renew")
        self.btn_enable_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enable_off.setGeometry(QtCore.QRect(1030, 70, 61, 30))
        self.btn_enable_off.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 15px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}")
        self.btn_enable_off.setObjectName("btn_enable_off")
        self.btn_enable_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enable_on.setGeometry(QtCore.QRect(890, 70, 61, 30))
        self.btn_enable_on.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 15px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}")
        self.btn_enable_on.setObjectName("btn_enable_on")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(576, 21, 44, 30))
        self.btn_stop.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_stop.setObjectName("btn_stop")
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file_name.setGeometry(QtCore.QRect(120, 21, 121, 30))
        self.lineEdit_file_name.setStyleSheet("  QLineEdit {text-align : center;\n"
"             background-color : white;\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}")
        self.lineEdit_file_name.setText("")
        self.lineEdit_file_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(830, 135, 41, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(830, 115, 41, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(870, 125, 16, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.btn_teach_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_teach_on.setGeometry(QtCore.QRect(890, 120, 61, 30))
        self.btn_teach_on.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 0px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}")
        self.btn_teach_on.setObjectName("btn_teach_on")
        self.btn_teach_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_teach_off.setGeometry(QtCore.QRect(1030, 120, 61, 30))
        self.btn_teach_off.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             border-radius: 0px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}")
        self.btn_teach_off.setObjectName("btn_teach_off")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(726, 21, 44, 30))
        self.btn_insert.setStyleSheet("QPushButton {text-align : center;\n"
"             background-color : rgb(216, 216, 216);\n"
"             font: bold;\n"
"             border-color: gray;\n"
"             border-width: 2px;\n"
"             padding: 6px;\n"
"             height : 14px;\n"
"             border-style: outset;\n"
"             font : 14px;}\n"
"QPushButton:pressed\n"
"                    {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.btn_insert.setObjectName("btn_insert")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "机械臂示教和运动控制"))
        self.btn_del.setText(_translate("MainWindow", "删除"))
        self.btn_move_up.setText(_translate("MainWindow", "上移"))
        self.btn_move_down.setText(_translate("MainWindow", "下移"))
        self.btn_stick.setText(_translate("MainWindow", "粘贴"))
        self.btn_copy.setText(_translate("MainWindow", "复制"))
        self.btn_clear.setText(_translate("MainWindow", "删除所有项"))
        self.btn_save_file.setText(_translate("MainWindow", "保存"))
        self.btn_open_file.setText(_translate("MainWindow", "打开"))
        self.label.setText(_translate("MainWindow", "关节1："))
        self.label_2.setText(_translate("MainWindow", "关节2："))
        self.label_3.setText(_translate("MainWindow", "关节3："))
        self.label_4.setText(_translate("MainWindow", "关节4："))
        self.label_5.setText(_translate("MainWindow", "夹 爪："))
        self.btn_j1_add.setText(_translate("MainWindow", "J1+"))
        self.btn_j1_subtract.setText(_translate("MainWindow", "J1-"))
        self.label_j1.setText(_translate("MainWindow", "0"))
        self.btn_j2_add.setText(_translate("MainWindow", "J2+"))
        self.btn_j2_subtract.setText(_translate("MainWindow", "J2-"))
        self.label_j2.setText(_translate("MainWindow", "0"))
        self.btn_j3_add.setText(_translate("MainWindow", "J3+"))
        self.label_j3.setText(_translate("MainWindow", "0"))
        self.btn_j3_subtract.setText(_translate("MainWindow", "J3-"))
        self.btn_j4_add.setText(_translate("MainWindow", "J4+"))
        self.label_j4.setText(_translate("MainWindow", "0"))
        self.btn_j4_subtract.setText(_translate("MainWindow", "J4-"))
        self.btn_clip_open.setText(_translate("MainWindow", "开"))
        self.btn_clip_close.setText(_translate("MainWindow", "关"))
        self.btn_reduce.setText(_translate("MainWindow", "复位"))
        self.btn_zero.setText(_translate("MainWindow", "归位"))
        self.btn_start.setText(_translate("MainWindow", "启动"))
        self.label_10.setText(_translate("MainWindow", "步 长："))
        self.btn_step_1.setText(_translate("MainWindow", "1"))
        self.btn_step_5.setText(_translate("MainWindow", "5"))
        self.btn_step_10.setText(_translate("MainWindow", "10"))
        self.btn_step_15.setText(_translate("MainWindow", "15"))
        self.label_12.setText(_translate("MainWindow", "速 度："))
        self.btn_speed_30.setText(_translate("MainWindow", "30"))
        self.btn_speed_100.setText(_translate("MainWindow", "100"))
        self.label_6.setText(_translate("MainWindow", "使 能："))
        self.lineEdit_speed.setText(_translate("MainWindow", "100"))
        self.lineEdit_step.setText(_translate("MainWindow", "5"))
        self.btn_run.setText(_translate("MainWindow", "运行"))
        self.lineEdit_recur.setText(_translate("MainWindow", "1"))
        self.btn_step.setText(_translate("MainWindow", "单步"))
        self.btn_add.setText(_translate("MainWindow", "添加"))
        self.btn_renew.setText(_translate("MainWindow", "更新"))
        self.btn_enable_off.setText(_translate("MainWindow", "OFF"))
        self.btn_enable_on.setText(_translate("MainWindow", "ON"))
        self.btn_stop.setText(_translate("MainWindow", "停止"))
        self.label_7.setText(_translate("MainWindow", "示 教："))
        self.label_8.setText(_translate("MainWindow", "拖 动"))
        self.label_9.setText(_translate("MainWindow", "："))
        self.btn_teach_on.setText(_translate("MainWindow", "ON"))
        self.btn_teach_off.setText(_translate("MainWindow", "OFF"))
        self.btn_insert.setText(_translate("MainWindow", "插入"))
