# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 580)
        MainWindow.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_show = QtWidgets.QLabel(self.centralwidget)
        self.Image_show.setGeometry(QtCore.QRect(0, 50, 640, 441))
        self.Image_show.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.Image_show.setText("")
        self.Image_show.setObjectName("Image_show")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 371, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.btn_close_detection = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close_detection.setEnabled(False)
        self.btn_close_detection.setGeometry(QtCore.QRect(380, 500, 121, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.btn_close_detection.setFont(font)
        self.btn_close_detection.setObjectName("btn_close_detection")
        self.btn_open_detection = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_detection.setGeometry(QtCore.QRect(520, 500, 121, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.btn_open_detection.setFont(font)
        self.btn_open_detection.setObjectName("btn_open_detection")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于视觉的车牌识别"))
        self.label_2.setText(_translate("MainWindow", "基于视觉的车牌识别"))
        self.btn_close_detection.setText(_translate("MainWindow", "关闭检测"))
        self.btn_open_detection.setText(_translate("MainWindow", "开启检测"))
