# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 524)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label1 = QtWidgets.QLabel(self.frame)
        self.label1.setGeometry(QtCore.QRect(0, 0, 471, 600))
        self.label1.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.label1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.label_imput_image = QtWidgets.QLabel(self.frame)
        self.label_imput_image.setGeometry(QtCore.QRect(0, 30, 471, 400))
        self.label_imput_image.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.label_imput_image.setText("")
        self.label_imput_image.setObjectName("label_imput_image")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(190, -1, 101, 31))
        font = QtGui.QFont()
        font.setFamily("7SEG76")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_open = QtWidgets.QPushButton(self.frame)
        self.pushButton_open.setGeometry(QtCore.QRect(30, 440, 121, 51))
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setGeometry(QtCore.QRect(300, 440, 121, 51))
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "myQt"))
        self.label_3.setText(_translate("MainWindow", "云台跟踪人脸"))
        self.pushButton_open.setText(_translate("MainWindow", "开启云台跟踪人脸"))
        self.pushButton_close.setText(_translate("MainWindow", "关闭相机"))
